//===========================================================================
// Verilog file generated by Clarity Designer    09/29/2020    01:16:09  
// Filename  : bytes_to_pixels_byte2pixel.v                                                
// IP package: Byte to Pixel Converter 1.3                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module bytes_to_pixels_byte2pixel (
    input  wire	                             reset_byte_n_i,
    input  wire	                             clk_byte_i,
    input  wire                              sp_en_i,	      // Short Packet Enable
    input  wire [5:0]                        dt_i,	          // Data Type
    input  wire                              lp_av_en_i,      // Long Packet of Active Video Enable
    input  wire	                             payload_en_i,    // paload enable
    input  wire [1*8-1:0]    payload_i,       // payload
    input  wire [15:0]                       wc_i,            // payload byte count

    input  wire	                             reset_pixel_n_i,
    input  wire	                             clk_pixel_i,
    output wire                              fv_o,            // Frame Valid in clk_pixel domain
    output wire                              lv_o,            // Line Valid in clk_pixel domain
    output wire [10*1-1:0] pd_o,            // picture data
    output wire [1:0]                        p_odd_o         // odd pixel indicator
);

byte2pixel 
#(
  .DSI_MODE          ("NONBURST_PULSES"),
  .VSA               (5),
  .HSA               (8),
  .CTRL_POL          ("POSITIVE"),
  .DT                (6'h2B),
  .RX_TYPE           ("CSI2"),
  .NUM_RX_LANE       (1),
  .RX_GEAR           (8),
  .PD_BUS_WIDTH      (10),
  .NUM_TX_CH         (1)

)
byte2pixel (
    .reset_byte_n_i          (reset_byte_n_i),
    .reset_pixel_n_i         (reset_pixel_n_i),
    .clk_byte_i              (clk_byte_i),
    .clk_pixel_i             (clk_pixel_i),
    .sp_en_i                 (sp_en_i),
    .dt_i                    (dt_i),
    .lp_av_en_i              (lp_av_en_i),
    .payload_en_i            (payload_en_i),
    .payload_i               (payload_i),
    .wc_i                    (wc_i),
    .sp2_en_i                (1'b0),
    .dt2_i                   (6'd0),
    .lp2_av_en_i             (1'b0),
    .wc2_i                   (16'd0),
    .vsync_o                 (),
    .hsync_o                 (),
    .de_o                    (),
    .fv_o                    (fv_o),
    .lv_o                    (lv_o),
    .write_cycle_o           (),
    .mem_we_o                (),
    .mem_re_o                (),
    .read_cycle_o            (),
    .mem_radr_o              (),
    .pd_o                    (pd_o),
    .p_odd_o                 (p_odd_o)
);

endmodule
