//===========================================================================
// Verilog file generated by Clarity Designer    09/29/2020    01:16:09  
// Filename  : bytes_to_pixels.v                                                
// IP package: Byte to Pixel Converter 1.3                           
// Copyright(c) 2017 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
////////////////////////////////////////////////////////
/// • Intermotion Technology
/// • B2P Changes
/// • Date MAY 2, 2019
/// • Arman Arshakyan
/// • Removed all directives and parameters declarations.
//////////////////////////////////////////////////////////////////////////////////

module bytes_to_pixels
(
    input  wire	                             reset_byte_n_i,
    input  wire	                             clk_byte_i,
    input  wire                              sp_en_i,	      // Short Packet Enable
    input  wire [5:0]                        dt_i,	          // Data Type
    input  wire                              lp_av_en_i,      // Long Packet of Active Video Enable
    input  wire	                             payload_en_i,    // paload enable
    input  wire [1*8-1:0]    payload_i,       // payload
    input  wire [15:0]                       wc_i,            // payload byte count

    input  wire	                             reset_pixel_n_i,
    input  wire	                             clk_pixel_i,
    output wire                              fv_o,            // Frame Valid in clk_pixel domain
    output wire                              lv_o,            // Line Valid in clk_pixel domain
    output wire [10*1-1:0] pd_o,            // picture data
    output wire [1:0]                        p_odd_o         // odd pixel indicator
);


/*synthesis translate_off*/
//  GSR GSR_INST (.GSR (1'b1));  // only for simulation purposes
// not included in official release, only used to check for compile errors
//`ifdef COMPILE_ONLY
//  PUR PUR_INST (.PUR (1'b1));  // only for simulation purposes
//`endif
/*synthesis translate_on*/

///// DPHY to CMOS Soft IP /////
  bytes_to_pixels_byte2pixel 
    byte2pixel_wrapper  (
    .reset_byte_n_i          (reset_byte_n_i),
    .reset_pixel_n_i         (reset_pixel_n_i),
    .clk_byte_i              (clk_byte_i),
    .clk_pixel_i             (clk_pixel_i),
    .sp_en_i                 (sp_en_i),
    .dt_i                    (dt_i),
    .lp_av_en_i              (lp_av_en_i),
    .payload_en_i            (payload_en_i),
    .payload_i               (payload_i),
    .wc_i                    (wc_i),
    .fv_o                    (fv_o),
    .lv_o                    (lv_o),
    .pd_o                    (pd_o),
    .p_odd_o                 (p_odd_o)
        );

endmodule
