/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 6.5 */
/* C:/lscc/diamond/3.11_x64/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch sn5w00 -type bram -wp 10 -rp 0011 -data_width 10 -num_rows 8 -rdata_width 10 -read_reg1 outreg -gsr DISABLED -sync_reset -memformat bin -cascade -1 -n pmi_ram_dpLbnonessdr1038103811880eab -pmi -lang verilog  */
/* Tue Sep 29 01:16:11 2020 */


`timescale 1 ns / 1 ps
module pmi_ram_dpLbnonessdr1038103811880eab (WrAddress, RdAddress, Data, 
    WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [2:0] WrAddress;
    input wire [2:0] RdAddress;
    input wire [9:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [9:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.CSDECODE_R = "0b000" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.CSDECODE_W = "0b001" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.RESETMODE = "SYNC" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.REGMODE = "OUTREG" ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.DATA_WIDTH_R = 18 ;
    defparam pmi_ram_dpLbnonessdr1038103811880eab_0_0_0.DATA_WIDTH_W = 18 ;
    PDPW8KE pmi_ram_dpLbnonessdr1038103811880eab_0_0_0 (.DI17(scuba_vlo), 
        .DI16(scuba_vlo), .DI15(scuba_vlo), .DI14(scuba_vlo), .DI13(scuba_vlo), 
        .DI12(scuba_vlo), .DI11(scuba_vlo), .DI10(scuba_vlo), .DI9(Data[9]), 
        .DI8(Data[8]), .DI7(Data[7]), .DI6(Data[6]), .DI5(Data[5]), .DI4(Data[4]), 
        .DI3(Data[3]), .DI2(Data[2]), .DI1(Data[1]), .DI0(Data[0]), .ADW8(scuba_vlo), 
        .ADW7(scuba_vlo), .ADW6(scuba_vlo), .ADW5(scuba_vlo), .ADW4(scuba_vlo), 
        .ADW3(scuba_vlo), .ADW2(WrAddress[2]), .ADW1(WrAddress[1]), .ADW0(WrAddress[0]), 
        .BE1(scuba_vhi), .BE0(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), 
        .CSW2(scuba_vlo), .CSW1(scuba_vlo), .CSW0(WE), .ADR12(scuba_vlo), 
        .ADR11(scuba_vlo), .ADR10(scuba_vlo), .ADR9(scuba_vlo), .ADR8(scuba_vlo), 
        .ADR7(scuba_vlo), .ADR6(RdAddress[2]), .ADR5(RdAddress[1]), .ADR4(RdAddress[0]), 
        .ADR3(scuba_vlo), .ADR2(scuba_vlo), .ADR1(scuba_vlo), .ADR0(scuba_vlo), 
        .CER(RdClockEn), .OCER(RdClockEn), .CLKR(RdClock), .CSR2(scuba_vlo), 
        .CSR1(scuba_vlo), .CSR0(scuba_vlo), .RST(Reset), .DO17(Q[8]), .DO16(Q[7]), 
        .DO15(Q[6]), .DO14(Q[5]), .DO13(Q[4]), .DO12(Q[3]), .DO11(Q[2]), 
        .DO10(Q[1]), .DO9(Q[0]), .DO8(), .DO7(), .DO6(), .DO5(), .DO4(), 
        .DO3(), .DO2(), .DO1(), .DO0(Q[9]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpLbnonessdr1038103811880eab__PMIP__8__10__10B" */
             /* synthesis MEM_INIT_FILE="" */;



    // exemplar begin
    // exemplar attribute pmi_ram_dpLbnonessdr1038103811880eab_0_0_0 MEM_LPC_FILE pmi_ram_dpLbnonessdr1038103811880eab__PMIP__8__10__10B
    // exemplar attribute pmi_ram_dpLbnonessdr1038103811880eab_0_0_0 MEM_INIT_FILE 
    // exemplar end

endmodule
