-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 5.8
--C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n LUT_FIFO -lang vhdl -synth lse -bus_exp 7 -bb -arch sn5w00 -type ebfifo -depth 2048 -width 10 -rwidth 10 -reset_rel SYNC -pe 10 -pe2 12 -pf 508 -pf2 506 -fdc C:/Users/Eduard/Documents/GitHub/fpga-projects/Crosslink_CSI2ToRaw10/source/clarity/camera/LUT_FIFO/LUT_FIFO.fdc 

-- Tue Nov 10 23:59:05 2020

library IEEE;
use IEEE.std_logic_1164.all;
library lifmd;
use lifmd.components.all;

entity LUT_FIFO is
    port (
        Data: in  std_logic_vector(9 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(9 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic; 
        AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end LUT_FIFO;

architecture Structure of LUT_FIFO is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal w_g2b_xor_cluster_2_1: std_logic;
    signal w_g2b_xor_cluster_2: std_logic;
    signal w_g2b_xor_cluster_1: std_logic;
    signal r_g2b_xor_cluster_2_1: std_logic;
    signal r_g2b_xor_cluster_2: std_logic;
    signal r_g2b_xor_cluster_1: std_logic;
    signal w_gdata_0: std_logic;
    signal w_gdata_1: std_logic;
    signal w_gdata_2: std_logic;
    signal w_gdata_3: std_logic;
    signal w_gdata_4: std_logic;
    signal w_gdata_5: std_logic;
    signal w_gdata_6: std_logic;
    signal w_gdata_7: std_logic;
    signal w_gdata_8: std_logic;
    signal w_gdata_9: std_logic;
    signal w_gdata_10: std_logic;
    signal wptr_0: std_logic;
    signal wptr_1: std_logic;
    signal wptr_2: std_logic;
    signal wptr_3: std_logic;
    signal wptr_4: std_logic;
    signal wptr_5: std_logic;
    signal wptr_6: std_logic;
    signal wptr_7: std_logic;
    signal wptr_8: std_logic;
    signal wptr_9: std_logic;
    signal wptr_10: std_logic;
    signal wptr_11: std_logic;
    signal r_gdata_0: std_logic;
    signal r_gdata_1: std_logic;
    signal r_gdata_2: std_logic;
    signal r_gdata_3: std_logic;
    signal r_gdata_4: std_logic;
    signal r_gdata_5: std_logic;
    signal r_gdata_6: std_logic;
    signal r_gdata_7: std_logic;
    signal r_gdata_8: std_logic;
    signal r_gdata_9: std_logic;
    signal r_gdata_10: std_logic;
    signal rptr_0: std_logic;
    signal rptr_1: std_logic;
    signal rptr_2: std_logic;
    signal rptr_3: std_logic;
    signal rptr_4: std_logic;
    signal rptr_5: std_logic;
    signal rptr_6: std_logic;
    signal rptr_7: std_logic;
    signal rptr_8: std_logic;
    signal rptr_9: std_logic;
    signal rptr_10: std_logic;
    signal rptr_11: std_logic;
    signal w_gcount_0: std_logic;
    signal w_gcount_1: std_logic;
    signal w_gcount_2: std_logic;
    signal w_gcount_3: std_logic;
    signal w_gcount_4: std_logic;
    signal w_gcount_5: std_logic;
    signal w_gcount_6: std_logic;
    signal w_gcount_7: std_logic;
    signal w_gcount_8: std_logic;
    signal w_gcount_9: std_logic;
    signal w_gcount_10: std_logic;
    signal w_gcount_11: std_logic;
    signal r_gcount_0: std_logic;
    signal r_gcount_1: std_logic;
    signal r_gcount_2: std_logic;
    signal r_gcount_3: std_logic;
    signal r_gcount_4: std_logic;
    signal r_gcount_5: std_logic;
    signal r_gcount_6: std_logic;
    signal r_gcount_7: std_logic;
    signal r_gcount_8: std_logic;
    signal r_gcount_9: std_logic;
    signal r_gcount_10: std_logic;
    signal r_gcount_11: std_logic;
    signal w_gcount_r20: std_logic;
    signal w_gcount_r0: std_logic;
    signal w_gcount_r21: std_logic;
    signal w_gcount_r1: std_logic;
    signal w_gcount_r22: std_logic;
    signal w_gcount_r2: std_logic;
    signal w_gcount_r23: std_logic;
    signal w_gcount_r3: std_logic;
    signal w_gcount_r24: std_logic;
    signal w_gcount_r4: std_logic;
    signal w_gcount_r25: std_logic;
    signal w_gcount_r5: std_logic;
    signal w_gcount_r26: std_logic;
    signal w_gcount_r6: std_logic;
    signal w_gcount_r27: std_logic;
    signal w_gcount_r7: std_logic;
    signal w_gcount_r28: std_logic;
    signal w_gcount_r8: std_logic;
    signal w_gcount_r29: std_logic;
    signal w_gcount_r9: std_logic;
    signal w_gcount_r210: std_logic;
    signal w_gcount_r10: std_logic;
    signal w_gcount_r211: std_logic;
    signal w_gcount_r11: std_logic;
    signal r_gcount_w20: std_logic;
    signal r_gcount_w0: std_logic;
    signal r_gcount_w21: std_logic;
    signal r_gcount_w1: std_logic;
    signal r_gcount_w22: std_logic;
    signal r_gcount_w2: std_logic;
    signal r_gcount_w23: std_logic;
    signal r_gcount_w3: std_logic;
    signal r_gcount_w24: std_logic;
    signal r_gcount_w4: std_logic;
    signal r_gcount_w25: std_logic;
    signal r_gcount_w5: std_logic;
    signal r_gcount_w26: std_logic;
    signal r_gcount_w6: std_logic;
    signal r_gcount_w27: std_logic;
    signal r_gcount_w7: std_logic;
    signal r_gcount_w28: std_logic;
    signal r_gcount_w8: std_logic;
    signal r_gcount_w29: std_logic;
    signal r_gcount_w9: std_logic;
    signal r_gcount_w210: std_logic;
    signal r_gcount_w10: std_logic;
    signal r_gcount_w211: std_logic;
    signal r_gcount_w11: std_logic;
    signal empty_i: std_logic;
    signal full_i: std_logic;
    signal ae: std_logic;
    signal rRst: std_logic;
    signal ae_d: std_logic;
    signal af: std_logic;
    signal af_d: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal w_gctr_ci: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co0: std_logic;
    signal iwcount_4: std_logic;
    signal iwcount_5: std_logic;
    signal co1: std_logic;
    signal iwcount_6: std_logic;
    signal iwcount_7: std_logic;
    signal co2: std_logic;
    signal iwcount_8: std_logic;
    signal iwcount_9: std_logic;
    signal co3: std_logic;
    signal iwcount_10: std_logic;
    signal iwcount_11: std_logic;
    signal co5: std_logic;
    signal co4: std_logic;
    signal wcount_11: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal r_gctr_ci: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co0_1: std_logic;
    signal ircount_4: std_logic;
    signal ircount_5: std_logic;
    signal co1_1: std_logic;
    signal ircount_6: std_logic;
    signal ircount_7: std_logic;
    signal co2_1: std_logic;
    signal ircount_8: std_logic;
    signal ircount_9: std_logic;
    signal co3_1: std_logic;
    signal ircount_10: std_logic;
    signal ircount_11: std_logic;
    signal co5_1: std_logic;
    signal co4_1: std_logic;
    signal rcount_11: std_logic;
    signal cmp_ci: std_logic;
    signal rcount_0: std_logic;
    signal rcount_1: std_logic;
    signal co0_2: std_logic;
    signal rcount_2: std_logic;
    signal rcount_3: std_logic;
    signal co1_2: std_logic;
    signal rcount_4: std_logic;
    signal rcount_5: std_logic;
    signal co2_2: std_logic;
    signal rcount_6: std_logic;
    signal rcount_7: std_logic;
    signal co3_2: std_logic;
    signal rcount_8: std_logic;
    signal rcount_9: std_logic;
    signal co4_2: std_logic;
    signal empty_cmp_clr: std_logic;
    signal rcount_10: std_logic;
    signal empty_cmp_set: std_logic;
    signal empty_d: std_logic;
    signal empty_d_c: std_logic;
    signal cmp_ci_1: std_logic;
    signal wcount_0: std_logic;
    signal wcount_1: std_logic;
    signal co0_3: std_logic;
    signal wcount_2: std_logic;
    signal wcount_3: std_logic;
    signal co1_3: std_logic;
    signal wcount_4: std_logic;
    signal wcount_5: std_logic;
    signal co2_3: std_logic;
    signal wcount_6: std_logic;
    signal wcount_7: std_logic;
    signal co3_3: std_logic;
    signal wcount_8: std_logic;
    signal wcount_9: std_logic;
    signal co4_3: std_logic;
    signal full_cmp_clr: std_logic;
    signal wcount_10: std_logic;
    signal full_cmp_set: std_logic;
    signal full_d: std_logic;
    signal full_d_c: std_logic;
    signal iae_setcount_0: std_logic;
    signal iae_setcount_1: std_logic;
    signal ae_set_ctr_ci: std_logic;
    signal iae_setcount_2: std_logic;
    signal iae_setcount_3: std_logic;
    signal co0_4: std_logic;
    signal iae_setcount_4: std_logic;
    signal iae_setcount_5: std_logic;
    signal co1_4: std_logic;
    signal iae_setcount_6: std_logic;
    signal iae_setcount_7: std_logic;
    signal co2_4: std_logic;
    signal iae_setcount_8: std_logic;
    signal iae_setcount_9: std_logic;
    signal co3_4: std_logic;
    signal iae_setcount_10: std_logic;
    signal iae_setcount_11: std_logic;
    signal co5_2: std_logic;
    signal co4_4: std_logic;
    signal ae_setcount_11: std_logic;
    signal cmp_ci_2: std_logic;
    signal ae_setcount_0: std_logic;
    signal ae_setcount_1: std_logic;
    signal co0_5: std_logic;
    signal ae_setcount_2: std_logic;
    signal ae_setcount_3: std_logic;
    signal co1_5: std_logic;
    signal ae_setcount_4: std_logic;
    signal ae_setcount_5: std_logic;
    signal co2_5: std_logic;
    signal ae_setcount_6: std_logic;
    signal ae_setcount_7: std_logic;
    signal co3_5: std_logic;
    signal ae_setcount_8: std_logic;
    signal ae_setcount_9: std_logic;
    signal co4_5: std_logic;
    signal ae_set_cmp_clr: std_logic;
    signal ae_setcount_10: std_logic;
    signal ae_set_cmp_set: std_logic;
    signal ae_set_d: std_logic;
    signal ae_set_d_c: std_logic;
    signal iae_clrcount_0: std_logic;
    signal iae_clrcount_1: std_logic;
    signal ae_clr_ctr_ci: std_logic;
    signal iae_clrcount_2: std_logic;
    signal iae_clrcount_3: std_logic;
    signal co0_6: std_logic;
    signal iae_clrcount_4: std_logic;
    signal iae_clrcount_5: std_logic;
    signal co1_6: std_logic;
    signal iae_clrcount_6: std_logic;
    signal iae_clrcount_7: std_logic;
    signal co2_6: std_logic;
    signal iae_clrcount_8: std_logic;
    signal iae_clrcount_9: std_logic;
    signal co3_6: std_logic;
    signal iae_clrcount_10: std_logic;
    signal iae_clrcount_11: std_logic;
    signal co5_3: std_logic;
    signal co4_6: std_logic;
    signal ae_clrcount_11: std_logic;
    signal rden_i: std_logic;
    signal cmp_ci_3: std_logic;
    signal wcount_r0: std_logic;
    signal wcount_r1: std_logic;
    signal ae_clrcount_0: std_logic;
    signal ae_clrcount_1: std_logic;
    signal co0_7: std_logic;
    signal wcount_r2: std_logic;
    signal wcount_r3: std_logic;
    signal ae_clrcount_2: std_logic;
    signal ae_clrcount_3: std_logic;
    signal co1_7: std_logic;
    signal wcount_r4: std_logic;
    signal wcount_r5: std_logic;
    signal ae_clrcount_4: std_logic;
    signal ae_clrcount_5: std_logic;
    signal co2_7: std_logic;
    signal wcount_r6: std_logic;
    signal wcount_r7: std_logic;
    signal ae_clrcount_6: std_logic;
    signal ae_clrcount_7: std_logic;
    signal co3_7: std_logic;
    signal w_g2b_xor_cluster_0: std_logic;
    signal wcount_r9: std_logic;
    signal ae_clrcount_8: std_logic;
    signal ae_clrcount_9: std_logic;
    signal co4_7: std_logic;
    signal wcount_r10: std_logic;
    signal ae_clr_cmp_clr: std_logic;
    signal ae_clrcount_10: std_logic;
    signal ae_clr_cmp_set: std_logic;
    signal ae_clr_d: std_logic;
    signal ae_clr_d_c: std_logic;
    signal iaf_setcount_0: std_logic;
    signal iaf_setcount_1: std_logic;
    signal af_set_ctr_ci: std_logic;
    signal iaf_setcount_2: std_logic;
    signal iaf_setcount_3: std_logic;
    signal co0_8: std_logic;
    signal iaf_setcount_4: std_logic;
    signal iaf_setcount_5: std_logic;
    signal co1_8: std_logic;
    signal iaf_setcount_6: std_logic;
    signal iaf_setcount_7: std_logic;
    signal co2_8: std_logic;
    signal iaf_setcount_8: std_logic;
    signal iaf_setcount_9: std_logic;
    signal co3_8: std_logic;
    signal iaf_setcount_10: std_logic;
    signal iaf_setcount_11: std_logic;
    signal co5_4: std_logic;
    signal co4_8: std_logic;
    signal af_setcount_11: std_logic;
    signal cmp_ci_4: std_logic;
    signal af_setcount_0: std_logic;
    signal af_setcount_1: std_logic;
    signal co0_9: std_logic;
    signal af_setcount_2: std_logic;
    signal af_setcount_3: std_logic;
    signal co1_9: std_logic;
    signal af_setcount_4: std_logic;
    signal af_setcount_5: std_logic;
    signal co2_9: std_logic;
    signal af_setcount_6: std_logic;
    signal af_setcount_7: std_logic;
    signal co3_9: std_logic;
    signal af_setcount_8: std_logic;
    signal af_setcount_9: std_logic;
    signal co4_9: std_logic;
    signal af_set_cmp_clr: std_logic;
    signal af_setcount_10: std_logic;
    signal af_set_cmp_set: std_logic;
    signal af_set: std_logic;
    signal af_set_c: std_logic;
    signal iaf_clrcount_0: std_logic;
    signal iaf_clrcount_1: std_logic;
    signal af_clr_ctr_ci: std_logic;
    signal iaf_clrcount_2: std_logic;
    signal iaf_clrcount_3: std_logic;
    signal co0_10: std_logic;
    signal iaf_clrcount_4: std_logic;
    signal iaf_clrcount_5: std_logic;
    signal co1_10: std_logic;
    signal iaf_clrcount_6: std_logic;
    signal iaf_clrcount_7: std_logic;
    signal co2_10: std_logic;
    signal iaf_clrcount_8: std_logic;
    signal iaf_clrcount_9: std_logic;
    signal co3_10: std_logic;
    signal iaf_clrcount_10: std_logic;
    signal iaf_clrcount_11: std_logic;
    signal co5_5: std_logic;
    signal co4_10: std_logic;
    signal af_clrcount_11: std_logic;
    signal wren_i: std_logic;
    signal cmp_ci_5: std_logic;
    signal rcount_w0: std_logic;
    signal rcount_w1: std_logic;
    signal af_clrcount_0: std_logic;
    signal af_clrcount_1: std_logic;
    signal co0_11: std_logic;
    signal rcount_w2: std_logic;
    signal rcount_w3: std_logic;
    signal af_clrcount_2: std_logic;
    signal af_clrcount_3: std_logic;
    signal co1_11: std_logic;
    signal rcount_w4: std_logic;
    signal rcount_w5: std_logic;
    signal af_clrcount_4: std_logic;
    signal af_clrcount_5: std_logic;
    signal co2_11: std_logic;
    signal rcount_w6: std_logic;
    signal rcount_w7: std_logic;
    signal af_clrcount_6: std_logic;
    signal af_clrcount_7: std_logic;
    signal co3_11: std_logic;
    signal r_g2b_xor_cluster_0: std_logic;
    signal rcount_w9: std_logic;
    signal af_clrcount_8: std_logic;
    signal af_clrcount_9: std_logic;
    signal co4_11: std_logic;
    signal rcount_w10: std_logic;
    signal af_clr_cmp_clr: std_logic;
    signal af_clrcount_10: std_logic;
    signal af_clr_cmp_set: std_logic;
    signal af_clr: std_logic;
    signal scuba_vhi: std_logic;
    signal scuba_vlo: std_logic;
    signal af_clr_c: std_logic;

    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of pdp_ram_0_0_2 : label is "LUT_FIFO.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_0_2 : label is "";
    attribute MEM_LPC_FILE of pdp_ram_0_1_1 : label is "LUT_FIFO.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_1_1 : label is "";
    attribute MEM_LPC_FILE of pdp_ram_0_2_0 : label is "LUT_FIFO.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_2_0 : label is "";
    attribute GSR of FF_171 : label is "ENABLED";
    attribute GSR of FF_170 : label is "ENABLED";
    attribute GSR of FF_169 : label is "ENABLED";
    attribute GSR of FF_168 : label is "ENABLED";
    attribute GSR of FF_167 : label is "ENABLED";
    attribute GSR of FF_166 : label is "ENABLED";
    attribute GSR of FF_165 : label is "ENABLED";
    attribute GSR of FF_164 : label is "ENABLED";
    attribute GSR of FF_163 : label is "ENABLED";
    attribute GSR of FF_162 : label is "ENABLED";
    attribute GSR of FF_161 : label is "ENABLED";
    attribute GSR of FF_160 : label is "ENABLED";
    attribute GSR of FF_159 : label is "ENABLED";
    attribute GSR of FF_158 : label is "ENABLED";
    attribute GSR of FF_157 : label is "ENABLED";
    attribute GSR of FF_156 : label is "ENABLED";
    attribute GSR of FF_155 : label is "ENABLED";
    attribute GSR of FF_154 : label is "ENABLED";
    attribute GSR of FF_153 : label is "ENABLED";
    attribute GSR of FF_152 : label is "ENABLED";
    attribute GSR of FF_151 : label is "ENABLED";
    attribute GSR of FF_150 : label is "ENABLED";
    attribute GSR of FF_149 : label is "ENABLED";
    attribute GSR of FF_148 : label is "ENABLED";
    attribute GSR of FF_147 : label is "ENABLED";
    attribute GSR of FF_146 : label is "ENABLED";
    attribute GSR of FF_145 : label is "ENABLED";
    attribute GSR of FF_144 : label is "ENABLED";
    attribute GSR of FF_143 : label is "ENABLED";
    attribute GSR of FF_142 : label is "ENABLED";
    attribute GSR of FF_141 : label is "ENABLED";
    attribute GSR of FF_140 : label is "ENABLED";
    attribute GSR of FF_139 : label is "ENABLED";
    attribute GSR of FF_138 : label is "ENABLED";
    attribute GSR of FF_137 : label is "ENABLED";
    attribute GSR of FF_136 : label is "ENABLED";
    attribute GSR of FF_135 : label is "ENABLED";
    attribute GSR of FF_134 : label is "ENABLED";
    attribute GSR of FF_133 : label is "ENABLED";
    attribute GSR of FF_132 : label is "ENABLED";
    attribute GSR of FF_131 : label is "ENABLED";
    attribute GSR of FF_130 : label is "ENABLED";
    attribute GSR of FF_129 : label is "ENABLED";
    attribute GSR of FF_128 : label is "ENABLED";
    attribute GSR of FF_127 : label is "ENABLED";
    attribute GSR of FF_126 : label is "ENABLED";
    attribute GSR of FF_125 : label is "ENABLED";
    attribute GSR of FF_124 : label is "ENABLED";
    attribute GSR of FF_123 : label is "ENABLED";
    attribute GSR of FF_122 : label is "ENABLED";
    attribute GSR of FF_121 : label is "ENABLED";
    attribute GSR of FF_120 : label is "ENABLED";
    attribute GSR of FF_119 : label is "ENABLED";
    attribute GSR of FF_118 : label is "ENABLED";
    attribute GSR of FF_117 : label is "ENABLED";
    attribute GSR of FF_116 : label is "ENABLED";
    attribute GSR of FF_115 : label is "ENABLED";
    attribute GSR of FF_114 : label is "ENABLED";
    attribute GSR of FF_113 : label is "ENABLED";
    attribute GSR of FF_112 : label is "ENABLED";
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    AND2_t24: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_1: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t23: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_0: INV
        port map (A=>empty_i, Z=>invout_0);

    OR2_t22: OR2
        port map (A=>Reset, B=>RPReset, Z=>rRst);

    XOR2_t21: XOR2
        port map (A=>wcount_0, B=>wcount_1, Z=>w_gdata_0);

    XOR2_t20: XOR2
        port map (A=>wcount_1, B=>wcount_2, Z=>w_gdata_1);

    XOR2_t19: XOR2
        port map (A=>wcount_2, B=>wcount_3, Z=>w_gdata_2);

    XOR2_t18: XOR2
        port map (A=>wcount_3, B=>wcount_4, Z=>w_gdata_3);

    XOR2_t17: XOR2
        port map (A=>wcount_4, B=>wcount_5, Z=>w_gdata_4);

    XOR2_t16: XOR2
        port map (A=>wcount_5, B=>wcount_6, Z=>w_gdata_5);

    XOR2_t15: XOR2
        port map (A=>wcount_6, B=>wcount_7, Z=>w_gdata_6);

    XOR2_t14: XOR2
        port map (A=>wcount_7, B=>wcount_8, Z=>w_gdata_7);

    XOR2_t13: XOR2
        port map (A=>wcount_8, B=>wcount_9, Z=>w_gdata_8);

    XOR2_t12: XOR2
        port map (A=>wcount_9, B=>wcount_10, Z=>w_gdata_9);

    XOR2_t11: XOR2
        port map (A=>wcount_10, B=>wcount_11, Z=>w_gdata_10);

    XOR2_t10: XOR2
        port map (A=>rcount_0, B=>rcount_1, Z=>r_gdata_0);

    XOR2_t9: XOR2
        port map (A=>rcount_1, B=>rcount_2, Z=>r_gdata_1);

    XOR2_t8: XOR2
        port map (A=>rcount_2, B=>rcount_3, Z=>r_gdata_2);

    XOR2_t7: XOR2
        port map (A=>rcount_3, B=>rcount_4, Z=>r_gdata_3);

    XOR2_t6: XOR2
        port map (A=>rcount_4, B=>rcount_5, Z=>r_gdata_4);

    XOR2_t5: XOR2
        port map (A=>rcount_5, B=>rcount_6, Z=>r_gdata_5);

    XOR2_t4: XOR2
        port map (A=>rcount_6, B=>rcount_7, Z=>r_gdata_6);

    XOR2_t3: XOR2
        port map (A=>rcount_7, B=>rcount_8, Z=>r_gdata_7);

    XOR2_t2: XOR2
        port map (A=>rcount_8, B=>rcount_9, Z=>r_gdata_8);

    XOR2_t1: XOR2
        port map (A=>rcount_9, B=>rcount_10, Z=>r_gdata_9);

    XOR2_t0: XOR2
        port map (A=>rcount_10, B=>rcount_11, Z=>r_gdata_10);

    LUT4_41: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r28, AD2=>w_gcount_r29, 
            AD1=>w_gcount_r210, AD0=>w_gcount_r211, 
            DO0=>w_g2b_xor_cluster_0);

    LUT4_40: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r24, AD2=>w_gcount_r25, 
            AD1=>w_gcount_r26, AD0=>w_gcount_r27, 
            DO0=>w_g2b_xor_cluster_1);

    LUT4_39: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r20, AD2=>w_gcount_r21, 
            AD1=>w_gcount_r22, AD0=>w_gcount_r23, 
            DO0=>w_g2b_xor_cluster_2);

    LUT4_38: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r210, AD2=>w_gcount_r211, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>wcount_r10);

    LUT4_37: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r29, AD2=>w_gcount_r210, 
            AD1=>w_gcount_r211, AD0=>scuba_vlo, DO0=>wcount_r9);

    LUT4_36: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r27, AD2=>w_gcount_r28, 
            AD1=>w_gcount_r29, AD0=>wcount_r10, DO0=>wcount_r7);

    LUT4_35: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r26, AD2=>w_gcount_r27, 
            AD1=>w_gcount_r28, AD0=>wcount_r9, DO0=>wcount_r6);

    LUT4_34: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r25, AD2=>w_gcount_r26, 
            AD1=>w_gcount_r27, AD0=>w_g2b_xor_cluster_0, DO0=>wcount_r5);

    LUT4_33: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>wcount_r4);

    LUT4_32: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r23, AD0=>scuba_vlo, DO0=>wcount_r3);

    LUT4_31: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r22, AD0=>w_gcount_r23, DO0=>wcount_r2);

    LUT4_30: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r21, AD2=>w_gcount_r22, 
            AD1=>w_gcount_r23, AD0=>scuba_vlo, 
            DO0=>w_g2b_xor_cluster_2_1);

    LUT4_29: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2_1, AD0=>scuba_vlo, DO0=>wcount_r1);

    LUT4_28: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_g2b_xor_cluster_2, AD0=>scuba_vlo, DO0=>wcount_r0);

    LUT4_27: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w28, AD2=>r_gcount_w29, 
            AD1=>r_gcount_w210, AD0=>r_gcount_w211, 
            DO0=>r_g2b_xor_cluster_0);

    LUT4_26: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w24, AD2=>r_gcount_w25, 
            AD1=>r_gcount_w26, AD0=>r_gcount_w27, 
            DO0=>r_g2b_xor_cluster_1);

    LUT4_25: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w20, AD2=>r_gcount_w21, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, 
            DO0=>r_g2b_xor_cluster_2);

    LUT4_24: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w210, AD2=>r_gcount_w211, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>rcount_w10);

    LUT4_23: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w29, AD2=>r_gcount_w210, 
            AD1=>r_gcount_w211, AD0=>scuba_vlo, DO0=>rcount_w9);

    LUT4_22: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w27, AD2=>r_gcount_w28, 
            AD1=>r_gcount_w29, AD0=>rcount_w10, DO0=>rcount_w7);

    LUT4_21: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w26, AD2=>r_gcount_w27, 
            AD1=>r_gcount_w28, AD0=>rcount_w9, DO0=>rcount_w6);

    LUT4_20: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w25, AD2=>r_gcount_w26, 
            AD1=>r_gcount_w27, AD0=>r_g2b_xor_cluster_0, DO0=>rcount_w5);

    LUT4_19: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>rcount_w4);

    LUT4_18: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, DO0=>rcount_w3);

    LUT4_17: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w22, AD0=>r_gcount_w23, DO0=>rcount_w2);

    LUT4_16: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w21, AD2=>r_gcount_w22, 
            AD1=>r_gcount_w23, AD0=>scuba_vlo, 
            DO0=>r_g2b_xor_cluster_2_1);

    LUT4_15: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_g2b_xor_cluster_2_1, AD0=>scuba_vlo, DO0=>rcount_w1);

    LUT4_14: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_g2b_xor_cluster_2, AD0=>scuba_vlo, DO0=>rcount_w0);

    LUT4_13: ROM16X1A
        generic map (initval=> X"0410")
        port map (AD3=>rptr_11, AD2=>rcount_11, AD1=>w_gcount_r211, 
            AD0=>scuba_vlo, DO0=>empty_cmp_set);

    LUT4_12: ROM16X1A
        generic map (initval=> X"1004")
        port map (AD3=>rptr_11, AD2=>rcount_11, AD1=>w_gcount_r211, 
            AD0=>scuba_vlo, DO0=>empty_cmp_clr);

    LUT4_11: ROM16X1A
        generic map (initval=> X"0140")
        port map (AD3=>wptr_11, AD2=>wcount_11, AD1=>r_gcount_w211, 
            AD0=>scuba_vlo, DO0=>full_cmp_set);

    LUT4_10: ROM16X1A
        generic map (initval=> X"4001")
        port map (AD3=>wptr_11, AD2=>wcount_11, AD1=>r_gcount_w211, 
            AD0=>scuba_vlo, DO0=>full_cmp_clr);

    LUT4_9: ROM16X1A
        generic map (initval=> X"13c8")
        port map (AD3=>ae_setcount_11, AD2=>rcount_11, 
            AD1=>w_gcount_r211, AD0=>rptr_11, DO0=>ae_set_cmp_set);

    LUT4_8: ROM16X1A
        generic map (initval=> X"2004")
        port map (AD3=>ae_setcount_11, AD2=>rcount_11, 
            AD1=>w_gcount_r211, AD0=>rptr_11, DO0=>ae_set_cmp_clr);

    LUT4_7: ROM16X1A
        generic map (initval=> X"13c8")
        port map (AD3=>ae_clrcount_11, AD2=>rcount_11, 
            AD1=>w_gcount_r211, AD0=>rptr_11, DO0=>ae_clr_cmp_set);

    LUT4_6: ROM16X1A
        generic map (initval=> X"2004")
        port map (AD3=>ae_clrcount_11, AD2=>rcount_11, 
            AD1=>w_gcount_r211, AD0=>rptr_11, DO0=>ae_clr_cmp_clr);

    LUT4_5: ROM16X1A
        generic map (initval=> X"4450")
        port map (AD3=>ae, AD2=>ae_set_d, AD1=>ae_clr_d, AD0=>scuba_vlo, 
            DO0=>ae_d);

    LUT4_4: ROM16X1A
        generic map (initval=> X"4c32")
        port map (AD3=>af_setcount_11, AD2=>wcount_11, 
            AD1=>r_gcount_w211, AD0=>wptr_11, DO0=>af_set_cmp_set);

    LUT4_3: ROM16X1A
        generic map (initval=> X"8001")
        port map (AD3=>af_setcount_11, AD2=>wcount_11, 
            AD1=>r_gcount_w211, AD0=>wptr_11, DO0=>af_set_cmp_clr);

    LUT4_2: ROM16X1A
        generic map (initval=> X"4c32")
        port map (AD3=>af_clrcount_11, AD2=>wcount_11, 
            AD1=>r_gcount_w211, AD0=>wptr_11, DO0=>af_clr_cmp_set);

    LUT4_1: ROM16X1A
        generic map (initval=> X"8001")
        port map (AD3=>af_clrcount_11, AD2=>wcount_11, 
            AD1=>r_gcount_w211, AD0=>wptr_11, DO0=>af_clr_cmp_clr);

    LUT4_0: ROM16X1A
        generic map (initval=> X"4450")
        port map (AD3=>af, AD2=>af_set, AD1=>af_clr, AD0=>scuba_vlo, 
            DO0=>af_d);

    pdp_ram_0_0_2: DP8KE
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(3), 
            DIA2=>Data(2), DIA1=>Data(1), DIA0=>Data(0), ADA12=>wptr_10, 
            ADA11=>wptr_9, ADA10=>wptr_8, ADA9=>wptr_7, ADA8=>wptr_6, 
            ADA7=>wptr_5, ADA6=>wptr_4, ADA5=>wptr_3, ADA4=>wptr_2, 
            ADA3=>wptr_1, ADA2=>wptr_0, ADA1=>scuba_vlo, ADA0=>scuba_vlo, 
            CEA=>wren_i, OCEA=>wren_i, CLKA=>WrClock, WEA=>scuba_vhi, 
            CSA2=>scuba_vlo, CSA1=>scuba_vlo, CSA0=>scuba_vlo, 
            RSTA=>Reset, DIB8=>scuba_vlo, DIB7=>scuba_vlo, 
            DIB6=>scuba_vlo, DIB5=>scuba_vlo, DIB4=>scuba_vlo, 
            DIB3=>scuba_vlo, DIB2=>scuba_vlo, DIB1=>scuba_vlo, 
            DIB0=>scuba_vlo, ADB12=>rptr_10, ADB11=>rptr_9, 
            ADB10=>rptr_8, ADB9=>rptr_7, ADB8=>rptr_6, ADB7=>rptr_5, 
            ADB6=>rptr_4, ADB5=>rptr_3, ADB4=>rptr_2, ADB3=>rptr_1, 
            ADB2=>rptr_0, ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>rden_i, 
            OCEB=>rden_i, CLKB=>RdClock, WEB=>scuba_vlo, CSB2=>scuba_vlo, 
            CSB1=>scuba_vlo, CSB0=>scuba_vlo, RSTB=>Reset, DOA8=>open, 
            DOA7=>open, DOA6=>open, DOA5=>open, DOA4=>open, DOA3=>open, 
            DOA2=>open, DOA1=>open, DOA0=>open, DOB8=>open, DOB7=>open, 
            DOB6=>open, DOB5=>open, DOB4=>open, DOB3=>Q(3), DOB2=>Q(2), 
            DOB1=>Q(1), DOB0=>Q(0));

    pdp_ram_0_1_1: DP8KE
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>Data(7), 
            DIA2=>Data(6), DIA1=>Data(5), DIA0=>Data(4), ADA12=>wptr_10, 
            ADA11=>wptr_9, ADA10=>wptr_8, ADA9=>wptr_7, ADA8=>wptr_6, 
            ADA7=>wptr_5, ADA6=>wptr_4, ADA5=>wptr_3, ADA4=>wptr_2, 
            ADA3=>wptr_1, ADA2=>wptr_0, ADA1=>scuba_vlo, ADA0=>scuba_vlo, 
            CEA=>wren_i, OCEA=>wren_i, CLKA=>WrClock, WEA=>scuba_vhi, 
            CSA2=>scuba_vlo, CSA1=>scuba_vlo, CSA0=>scuba_vlo, 
            RSTA=>Reset, DIB8=>scuba_vlo, DIB7=>scuba_vlo, 
            DIB6=>scuba_vlo, DIB5=>scuba_vlo, DIB4=>scuba_vlo, 
            DIB3=>scuba_vlo, DIB2=>scuba_vlo, DIB1=>scuba_vlo, 
            DIB0=>scuba_vlo, ADB12=>rptr_10, ADB11=>rptr_9, 
            ADB10=>rptr_8, ADB9=>rptr_7, ADB8=>rptr_6, ADB7=>rptr_5, 
            ADB6=>rptr_4, ADB5=>rptr_3, ADB4=>rptr_2, ADB3=>rptr_1, 
            ADB2=>rptr_0, ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>rden_i, 
            OCEB=>rden_i, CLKB=>RdClock, WEB=>scuba_vlo, CSB2=>scuba_vlo, 
            CSB1=>scuba_vlo, CSB0=>scuba_vlo, RSTB=>Reset, DOA8=>open, 
            DOA7=>open, DOA6=>open, DOA5=>open, DOA4=>open, DOA3=>open, 
            DOA2=>open, DOA1=>open, DOA0=>open, DOB8=>open, DOB7=>open, 
            DOB6=>open, DOB5=>open, DOB4=>open, DOB3=>Q(7), DOB2=>Q(6), 
            DOB1=>Q(5), DOB0=>Q(4));

    pdp_ram_0_2_0: DP8KE
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL", 
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC", 
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  4, 
        DATA_WIDTH_A=>  4)
        port map (DIA8=>scuba_vlo, DIA7=>scuba_vlo, DIA6=>scuba_vlo, 
            DIA5=>scuba_vlo, DIA4=>scuba_vlo, DIA3=>scuba_vlo, 
            DIA2=>scuba_vlo, DIA1=>Data(9), DIA0=>Data(8), 
            ADA12=>wptr_10, ADA11=>wptr_9, ADA10=>wptr_8, ADA9=>wptr_7, 
            ADA8=>wptr_6, ADA7=>wptr_5, ADA6=>wptr_4, ADA5=>wptr_3, 
            ADA4=>wptr_2, ADA3=>wptr_1, ADA2=>wptr_0, ADA1=>scuba_vlo, 
            ADA0=>scuba_vlo, CEA=>wren_i, OCEA=>wren_i, CLKA=>WrClock, 
            WEA=>scuba_vhi, CSA2=>scuba_vlo, CSA1=>scuba_vlo, 
            CSA0=>scuba_vlo, RSTA=>Reset, DIB8=>scuba_vlo, 
            DIB7=>scuba_vlo, DIB6=>scuba_vlo, DIB5=>scuba_vlo, 
            DIB4=>scuba_vlo, DIB3=>scuba_vlo, DIB2=>scuba_vlo, 
            DIB1=>scuba_vlo, DIB0=>scuba_vlo, ADB12=>rptr_10, 
            ADB11=>rptr_9, ADB10=>rptr_8, ADB9=>rptr_7, ADB8=>rptr_6, 
            ADB7=>rptr_5, ADB6=>rptr_4, ADB5=>rptr_3, ADB4=>rptr_2, 
            ADB3=>rptr_1, ADB2=>rptr_0, ADB1=>scuba_vlo, ADB0=>scuba_vlo, 
            CEB=>rden_i, OCEB=>rden_i, CLKB=>RdClock, WEB=>scuba_vlo, 
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>scuba_vlo, 
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open, 
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open, 
            DOB8=>open, DOB7=>open, DOB6=>open, DOB5=>open, DOB4=>open, 
            DOB3=>open, DOB2=>open, DOB1=>Q(9), DOB0=>Q(8));

    FF_171: FD1P3BX
        port map (D=>iwcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>wcount_0);

    FF_170: FD1P3DX
        port map (D=>iwcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_1);

    FF_169: FD1P3DX
        port map (D=>iwcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_2);

    FF_168: FD1P3DX
        port map (D=>iwcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_3);

    FF_167: FD1P3DX
        port map (D=>iwcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_4);

    FF_166: FD1P3DX
        port map (D=>iwcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_5);

    FF_165: FD1P3DX
        port map (D=>iwcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_6);

    FF_164: FD1P3DX
        port map (D=>iwcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_7);

    FF_163: FD1P3DX
        port map (D=>iwcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_8);

    FF_162: FD1P3DX
        port map (D=>iwcount_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_9);

    FF_161: FD1P3DX
        port map (D=>iwcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_10);

    FF_160: FD1P3DX
        port map (D=>iwcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_11);

    FF_159: FD1P3DX
        port map (D=>w_gdata_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_0);

    FF_158: FD1P3DX
        port map (D=>w_gdata_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_1);

    FF_157: FD1P3DX
        port map (D=>w_gdata_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_2);

    FF_156: FD1P3DX
        port map (D=>w_gdata_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_3);

    FF_155: FD1P3DX
        port map (D=>w_gdata_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_4);

    FF_154: FD1P3DX
        port map (D=>w_gdata_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_5);

    FF_153: FD1P3DX
        port map (D=>w_gdata_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_6);

    FF_152: FD1P3DX
        port map (D=>w_gdata_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_7);

    FF_151: FD1P3DX
        port map (D=>w_gdata_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_8);

    FF_150: FD1P3DX
        port map (D=>w_gdata_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_9);

    FF_149: FD1P3DX
        port map (D=>w_gdata_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_10);

    FF_148: FD1P3DX
        port map (D=>wcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_11);

    FF_147: FD1P3DX
        port map (D=>wcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_0);

    FF_146: FD1P3DX
        port map (D=>wcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_1);

    FF_145: FD1P3DX
        port map (D=>wcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_2);

    FF_144: FD1P3DX
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_3);

    FF_143: FD1P3DX
        port map (D=>wcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_4);

    FF_142: FD1P3DX
        port map (D=>wcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_5);

    FF_141: FD1P3DX
        port map (D=>wcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_6);

    FF_140: FD1P3DX
        port map (D=>wcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_7);

    FF_139: FD1P3DX
        port map (D=>wcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_8);

    FF_138: FD1P3DX
        port map (D=>wcount_9, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_9);

    FF_137: FD1P3DX
        port map (D=>wcount_10, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_10);

    FF_136: FD1P3DX
        port map (D=>wcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_11);

    FF_135: FD1P3BX
        port map (D=>ircount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>rcount_0);

    FF_134: FD1P3DX
        port map (D=>ircount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_1);

    FF_133: FD1P3DX
        port map (D=>ircount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_2);

    FF_132: FD1P3DX
        port map (D=>ircount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_3);

    FF_131: FD1P3DX
        port map (D=>ircount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_4);

    FF_130: FD1P3DX
        port map (D=>ircount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_5);

    FF_129: FD1P3DX
        port map (D=>ircount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_6);

    FF_128: FD1P3DX
        port map (D=>ircount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_7);

    FF_127: FD1P3DX
        port map (D=>ircount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_8);

    FF_126: FD1P3DX
        port map (D=>ircount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_9);

    FF_125: FD1P3DX
        port map (D=>ircount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_10);

    FF_124: FD1P3DX
        port map (D=>ircount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_11);

    FF_123: FD1P3DX
        port map (D=>r_gdata_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_0);

    FF_122: FD1P3DX
        port map (D=>r_gdata_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_1);

    FF_121: FD1P3DX
        port map (D=>r_gdata_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_2);

    FF_120: FD1P3DX
        port map (D=>r_gdata_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_3);

    FF_119: FD1P3DX
        port map (D=>r_gdata_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_4);

    FF_118: FD1P3DX
        port map (D=>r_gdata_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_5);

    FF_117: FD1P3DX
        port map (D=>r_gdata_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_6);

    FF_116: FD1P3DX
        port map (D=>r_gdata_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_7);

    FF_115: FD1P3DX
        port map (D=>r_gdata_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_8);

    FF_114: FD1P3DX
        port map (D=>r_gdata_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_9);

    FF_113: FD1P3DX
        port map (D=>r_gdata_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_10);

    FF_112: FD1P3DX
        port map (D=>rcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_11);

    FF_111: FD1P3DX
        port map (D=>rcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_0);

    FF_110: FD1P3DX
        port map (D=>rcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_1);

    FF_109: FD1P3DX
        port map (D=>rcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_2);

    FF_108: FD1P3DX
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_3);

    FF_107: FD1P3DX
        port map (D=>rcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_4);

    FF_106: FD1P3DX
        port map (D=>rcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_5);

    FF_105: FD1P3DX
        port map (D=>rcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_6);

    FF_104: FD1P3DX
        port map (D=>rcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_7);

    FF_103: FD1P3DX
        port map (D=>rcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_8);

    FF_102: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_9);

    FF_101: FD1P3DX
        port map (D=>rcount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_10);

    FF_100: FD1P3DX
        port map (D=>rcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_11);

    FF_99: FD1S3DX
        port map (D=>w_gcount_0, CK=>RdClock, CD=>Reset, Q=>w_gcount_r0);

    FF_98: FD1S3DX
        port map (D=>w_gcount_1, CK=>RdClock, CD=>Reset, Q=>w_gcount_r1);

    FF_97: FD1S3DX
        port map (D=>w_gcount_2, CK=>RdClock, CD=>Reset, Q=>w_gcount_r2);

    FF_96: FD1S3DX
        port map (D=>w_gcount_3, CK=>RdClock, CD=>Reset, Q=>w_gcount_r3);

    FF_95: FD1S3DX
        port map (D=>w_gcount_4, CK=>RdClock, CD=>Reset, Q=>w_gcount_r4);

    FF_94: FD1S3DX
        port map (D=>w_gcount_5, CK=>RdClock, CD=>Reset, Q=>w_gcount_r5);

    FF_93: FD1S3DX
        port map (D=>w_gcount_6, CK=>RdClock, CD=>Reset, Q=>w_gcount_r6);

    FF_92: FD1S3DX
        port map (D=>w_gcount_7, CK=>RdClock, CD=>Reset, Q=>w_gcount_r7);

    FF_91: FD1S3DX
        port map (D=>w_gcount_8, CK=>RdClock, CD=>Reset, Q=>w_gcount_r8);

    FF_90: FD1S3DX
        port map (D=>w_gcount_9, CK=>RdClock, CD=>Reset, Q=>w_gcount_r9);

    FF_89: FD1S3DX
        port map (D=>w_gcount_10, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r10);

    FF_88: FD1S3DX
        port map (D=>w_gcount_11, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r11);

    FF_87: FD1S3DX
        port map (D=>r_gcount_0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w0);

    FF_86: FD1S3DX
        port map (D=>r_gcount_1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w1);

    FF_85: FD1S3DX
        port map (D=>r_gcount_2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w2);

    FF_84: FD1S3DX
        port map (D=>r_gcount_3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w3);

    FF_83: FD1S3DX
        port map (D=>r_gcount_4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w4);

    FF_82: FD1S3DX
        port map (D=>r_gcount_5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w5);

    FF_81: FD1S3DX
        port map (D=>r_gcount_6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w6);

    FF_80: FD1S3DX
        port map (D=>r_gcount_7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w7);

    FF_79: FD1S3DX
        port map (D=>r_gcount_8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w8);

    FF_78: FD1S3DX
        port map (D=>r_gcount_9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w9);

    FF_77: FD1S3DX
        port map (D=>r_gcount_10, CK=>WrClock, CD=>rRst, Q=>r_gcount_w10);

    FF_76: FD1S3DX
        port map (D=>r_gcount_11, CK=>WrClock, CD=>rRst, Q=>r_gcount_w11);

    FF_75: FD1S3DX
        port map (D=>w_gcount_r0, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r20);

    FF_74: FD1S3DX
        port map (D=>w_gcount_r1, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r21);

    FF_73: FD1S3DX
        port map (D=>w_gcount_r2, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r22);

    FF_72: FD1S3DX
        port map (D=>w_gcount_r3, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r23);

    FF_71: FD1S3DX
        port map (D=>w_gcount_r4, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r24);

    FF_70: FD1S3DX
        port map (D=>w_gcount_r5, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r25);

    FF_69: FD1S3DX
        port map (D=>w_gcount_r6, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r26);

    FF_68: FD1S3DX
        port map (D=>w_gcount_r7, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r27);

    FF_67: FD1S3DX
        port map (D=>w_gcount_r8, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r28);

    FF_66: FD1S3DX
        port map (D=>w_gcount_r9, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r29);

    FF_65: FD1S3DX
        port map (D=>w_gcount_r10, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r210);

    FF_64: FD1S3DX
        port map (D=>w_gcount_r11, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r211);

    FF_63: FD1S3DX
        port map (D=>r_gcount_w0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w20);

    FF_62: FD1S3DX
        port map (D=>r_gcount_w1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w21);

    FF_61: FD1S3DX
        port map (D=>r_gcount_w2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w22);

    FF_60: FD1S3DX
        port map (D=>r_gcount_w3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w23);

    FF_59: FD1S3DX
        port map (D=>r_gcount_w4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w24);

    FF_58: FD1S3DX
        port map (D=>r_gcount_w5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w25);

    FF_57: FD1S3DX
        port map (D=>r_gcount_w6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w26);

    FF_56: FD1S3DX
        port map (D=>r_gcount_w7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w27);

    FF_55: FD1S3DX
        port map (D=>r_gcount_w8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w28);

    FF_54: FD1S3DX
        port map (D=>r_gcount_w9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w29);

    FF_53: FD1S3DX
        port map (D=>r_gcount_w10, CK=>WrClock, CD=>rRst, 
            Q=>r_gcount_w210);

    FF_52: FD1S3DX
        port map (D=>r_gcount_w11, CK=>WrClock, CD=>rRst, 
            Q=>r_gcount_w211);

    FF_51: FD1S3BX
        port map (D=>empty_d, CK=>RdClock, PD=>rRst, Q=>empty_i);

    FF_50: FD1S3DX
        port map (D=>full_d, CK=>WrClock, CD=>Reset, Q=>full_i);

    FF_49: FD1P3BX
        port map (D=>iae_setcount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_0);

    FF_48: FD1P3BX
        port map (D=>iae_setcount_1, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_1);

    FF_47: FD1P3DX
        port map (D=>iae_setcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_2);

    FF_46: FD1P3BX
        port map (D=>iae_setcount_3, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_setcount_3);

    FF_45: FD1P3DX
        port map (D=>iae_setcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_4);

    FF_44: FD1P3DX
        port map (D=>iae_setcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_5);

    FF_43: FD1P3DX
        port map (D=>iae_setcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_6);

    FF_42: FD1P3DX
        port map (D=>iae_setcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_7);

    FF_41: FD1P3DX
        port map (D=>iae_setcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_8);

    FF_40: FD1P3DX
        port map (D=>iae_setcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_9);

    FF_39: FD1P3DX
        port map (D=>iae_setcount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_10);

    FF_38: FD1P3DX
        port map (D=>iae_setcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_setcount_11);

    FF_37: FD1P3BX
        port map (D=>iae_clrcount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_clrcount_0);

    FF_36: FD1P3DX
        port map (D=>iae_clrcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_1);

    FF_35: FD1P3BX
        port map (D=>iae_clrcount_2, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_clrcount_2);

    FF_34: FD1P3BX
        port map (D=>iae_clrcount_3, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>ae_clrcount_3);

    FF_33: FD1P3DX
        port map (D=>iae_clrcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_4);

    FF_32: FD1P3DX
        port map (D=>iae_clrcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_5);

    FF_31: FD1P3DX
        port map (D=>iae_clrcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_6);

    FF_30: FD1P3DX
        port map (D=>iae_clrcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_7);

    FF_29: FD1P3DX
        port map (D=>iae_clrcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_8);

    FF_28: FD1P3DX
        port map (D=>iae_clrcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_9);

    FF_27: FD1P3DX
        port map (D=>iae_clrcount_10, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_10);

    FF_26: FD1P3DX
        port map (D=>iae_clrcount_11, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>ae_clrcount_11);

    FF_25: FD1S3BX
        port map (D=>ae_d, CK=>RdClock, PD=>rRst, Q=>ae);

    FF_24: FD1P3BX
        port map (D=>iaf_setcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_0);

    FF_23: FD1P3DX
        port map (D=>iaf_setcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_1);

    FF_22: FD1P3BX
        port map (D=>iaf_setcount_2, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_2);

    FF_21: FD1P3DX
        port map (D=>iaf_setcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_3);

    FF_20: FD1P3DX
        port map (D=>iaf_setcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_4);

    FF_19: FD1P3DX
        port map (D=>iaf_setcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_5);

    FF_18: FD1P3DX
        port map (D=>iaf_setcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_6);

    FF_17: FD1P3DX
        port map (D=>iaf_setcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_7);

    FF_16: FD1P3DX
        port map (D=>iaf_setcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_8);

    FF_15: FD1P3BX
        port map (D=>iaf_setcount_9, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_9);

    FF_14: FD1P3BX
        port map (D=>iaf_setcount_10, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_setcount_10);

    FF_13: FD1P3DX
        port map (D=>iaf_setcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_setcount_11);

    FF_12: FD1P3BX
        port map (D=>iaf_clrcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_0);

    FF_11: FD1P3BX
        port map (D=>iaf_clrcount_1, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_1);

    FF_10: FD1P3BX
        port map (D=>iaf_clrcount_2, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_2);

    FF_9: FD1P3DX
        port map (D=>iaf_clrcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_3);

    FF_8: FD1P3DX
        port map (D=>iaf_clrcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_4);

    FF_7: FD1P3DX
        port map (D=>iaf_clrcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_5);

    FF_6: FD1P3DX
        port map (D=>iaf_clrcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_6);

    FF_5: FD1P3DX
        port map (D=>iaf_clrcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_7);

    FF_4: FD1P3DX
        port map (D=>iaf_clrcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_8);

    FF_3: FD1P3BX
        port map (D=>iaf_clrcount_9, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_9);

    FF_2: FD1P3BX
        port map (D=>iaf_clrcount_10, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>af_clrcount_10);

    FF_1: FD1P3DX
        port map (D=>iaf_clrcount_11, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>af_clrcount_11);

    FF_0: FD1S3DX
        port map (D=>af_d, CK=>WrClock, CD=>Reset, Q=>af);

    w_gctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>w_gctr_ci);

    w_gctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_0, A1=>wcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>w_gctr_ci, S0=>iwcount_0, S1=>iwcount_1, 
            COUT=>co0);

    w_gctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_2, A1=>wcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0, S0=>iwcount_2, S1=>iwcount_3, 
            COUT=>co1);

    w_gctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_4, A1=>wcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1, S0=>iwcount_4, S1=>iwcount_5, 
            COUT=>co2);

    w_gctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_6, A1=>wcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2, S0=>iwcount_6, S1=>iwcount_7, 
            COUT=>co3);

    w_gctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_8, A1=>wcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3, S0=>iwcount_8, S1=>iwcount_9, 
            COUT=>co4);

    w_gctr_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_10, A1=>wcount_11, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4, S0=>iwcount_10, S1=>iwcount_11, 
            COUT=>co5);

    r_gctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>r_gctr_ci);

    r_gctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_0, A1=>rcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>r_gctr_ci, S0=>ircount_0, S1=>ircount_1, 
            COUT=>co0_1);

    r_gctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_2, A1=>rcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_1, S0=>ircount_2, S1=>ircount_3, 
            COUT=>co1_1);

    r_gctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_4, A1=>rcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_1, S0=>ircount_4, S1=>ircount_5, 
            COUT=>co2_1);

    r_gctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_6, A1=>rcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_1, S0=>ircount_6, S1=>ircount_7, 
            COUT=>co3_1);

    r_gctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_8, A1=>rcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_1, S0=>ircount_8, S1=>ircount_9, 
            COUT=>co4_1);

    r_gctr_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_10, A1=>rcount_11, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_1, S0=>ircount_10, S1=>ircount_11, 
            COUT=>co5_1);

    empty_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci);

    empty_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_0, A1=>rcount_1, B0=>wcount_r0, 
            B1=>wcount_r1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci, S0=>open, S1=>open, COUT=>co0_2);

    empty_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_2, A1=>rcount_3, B0=>wcount_r2, 
            B1=>wcount_r3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_2, S0=>open, S1=>open, COUT=>co1_2);

    empty_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_4, A1=>rcount_5, B0=>wcount_r4, 
            B1=>wcount_r5, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_2, S0=>open, S1=>open, COUT=>co2_2);

    empty_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_6, A1=>rcount_7, B0=>wcount_r6, 
            B1=>wcount_r7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_2, S0=>open, S1=>open, COUT=>co3_2);

    empty_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_8, A1=>rcount_9, B0=>w_g2b_xor_cluster_0, 
            B1=>wcount_r9, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_2, S0=>open, S1=>open, COUT=>co4_2);

    empty_cmp_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_10, A1=>empty_cmp_set, B0=>wcount_r10, 
            B1=>empty_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co4_2, S0=>open, S1=>open, 
            COUT=>empty_d_c);

    a0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>empty_d_c, S0=>empty_d, S1=>open, 
            COUT=>open);

    full_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_1);

    full_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_0, A1=>wcount_1, B0=>rcount_w0, 
            B1=>rcount_w1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci_1, S0=>open, S1=>open, 
            COUT=>co0_3);

    full_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_2, A1=>wcount_3, B0=>rcount_w2, 
            B1=>rcount_w3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_3, S0=>open, S1=>open, COUT=>co1_3);

    full_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_4, A1=>wcount_5, B0=>rcount_w4, 
            B1=>rcount_w5, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_3, S0=>open, S1=>open, COUT=>co2_3);

    full_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_6, A1=>wcount_7, B0=>rcount_w6, 
            B1=>rcount_w7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_3, S0=>open, S1=>open, COUT=>co3_3);

    full_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_8, A1=>wcount_9, B0=>r_g2b_xor_cluster_0, 
            B1=>rcount_w9, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_3, S0=>open, S1=>open, COUT=>co4_3);

    full_cmp_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_10, A1=>full_cmp_set, B0=>rcount_w10, 
            B1=>full_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co4_3, S0=>open, S1=>open, 
            COUT=>full_d_c);

    a1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>full_d_c, S0=>full_d, S1=>open, 
            COUT=>open);

    ae_set_ctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, 
            COUT=>ae_set_ctr_ci);

    ae_set_ctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_setcount_0, A1=>ae_setcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>ae_set_ctr_ci, S0=>iae_setcount_0, 
            S1=>iae_setcount_1, COUT=>co0_4);

    ae_set_ctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_setcount_2, A1=>ae_setcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_4, S0=>iae_setcount_2, 
            S1=>iae_setcount_3, COUT=>co1_4);

    ae_set_ctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_setcount_4, A1=>ae_setcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_4, S0=>iae_setcount_4, 
            S1=>iae_setcount_5, COUT=>co2_4);

    ae_set_ctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_setcount_6, A1=>ae_setcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_4, S0=>iae_setcount_6, 
            S1=>iae_setcount_7, COUT=>co3_4);

    ae_set_ctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_setcount_8, A1=>ae_setcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_4, S0=>iae_setcount_8, 
            S1=>iae_setcount_9, COUT=>co4_4);

    ae_set_ctr_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_setcount_10, A1=>ae_setcount_11, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_4, S0=>iae_setcount_10, 
            S1=>iae_setcount_11, COUT=>co5_2);

    ae_set_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_2);

    ae_set_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_setcount_0, A1=>ae_setcount_1, B0=>wcount_r0, 
            B1=>wcount_r1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci_2, S0=>open, S1=>open, 
            COUT=>co0_5);

    ae_set_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_setcount_2, A1=>ae_setcount_3, B0=>wcount_r2, 
            B1=>wcount_r3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_5, S0=>open, S1=>open, COUT=>co1_5);

    ae_set_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_setcount_4, A1=>ae_setcount_5, B0=>wcount_r4, 
            B1=>wcount_r5, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_5, S0=>open, S1=>open, COUT=>co2_5);

    ae_set_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_setcount_6, A1=>ae_setcount_7, B0=>wcount_r6, 
            B1=>wcount_r7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_5, S0=>open, S1=>open, COUT=>co3_5);

    ae_set_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_setcount_8, A1=>ae_setcount_9, 
            B0=>w_g2b_xor_cluster_0, B1=>wcount_r9, C0=>scuba_vhi, 
            C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co3_5, 
            S0=>open, S1=>open, COUT=>co4_5);

    ae_set_cmp_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_setcount_10, A1=>ae_set_cmp_set, B0=>wcount_r10, 
            B1=>ae_set_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co4_5, S0=>open, S1=>open, 
            COUT=>ae_set_d_c);

    a2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>ae_set_d_c, S0=>ae_set_d, S1=>open, 
            COUT=>open);

    ae_clr_ctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, 
            COUT=>ae_clr_ctr_ci);

    ae_clr_ctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_clrcount_0, A1=>ae_clrcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>ae_clr_ctr_ci, S0=>iae_clrcount_0, 
            S1=>iae_clrcount_1, COUT=>co0_6);

    ae_clr_ctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_clrcount_2, A1=>ae_clrcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_6, S0=>iae_clrcount_2, 
            S1=>iae_clrcount_3, COUT=>co1_6);

    ae_clr_ctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_clrcount_4, A1=>ae_clrcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_6, S0=>iae_clrcount_4, 
            S1=>iae_clrcount_5, COUT=>co2_6);

    ae_clr_ctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_clrcount_6, A1=>ae_clrcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_6, S0=>iae_clrcount_6, 
            S1=>iae_clrcount_7, COUT=>co3_6);

    ae_clr_ctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_clrcount_8, A1=>ae_clrcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_6, S0=>iae_clrcount_8, 
            S1=>iae_clrcount_9, COUT=>co4_6);

    ae_clr_ctr_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>ae_clrcount_10, A1=>ae_clrcount_11, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_6, S0=>iae_clrcount_10, 
            S1=>iae_clrcount_11, COUT=>co5_3);

    ae_clr_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_3);

    ae_clr_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_clrcount_0, A1=>ae_clrcount_1, B0=>wcount_r0, 
            B1=>wcount_r1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci_3, S0=>open, S1=>open, 
            COUT=>co0_7);

    ae_clr_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_clrcount_2, A1=>ae_clrcount_3, B0=>wcount_r2, 
            B1=>wcount_r3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_7, S0=>open, S1=>open, COUT=>co1_7);

    ae_clr_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_clrcount_4, A1=>ae_clrcount_5, B0=>wcount_r4, 
            B1=>wcount_r5, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_7, S0=>open, S1=>open, COUT=>co2_7);

    ae_clr_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_clrcount_6, A1=>ae_clrcount_7, B0=>wcount_r6, 
            B1=>wcount_r7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_7, S0=>open, S1=>open, COUT=>co3_7);

    ae_clr_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_clrcount_8, A1=>ae_clrcount_9, 
            B0=>w_g2b_xor_cluster_0, B1=>wcount_r9, C0=>scuba_vhi, 
            C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co3_7, 
            S0=>open, S1=>open, COUT=>co4_7);

    ae_clr_cmp_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>ae_clrcount_10, A1=>ae_clr_cmp_set, B0=>wcount_r10, 
            B1=>ae_clr_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co4_7, S0=>open, S1=>open, 
            COUT=>ae_clr_d_c);

    a3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>ae_clr_d_c, S0=>ae_clr_d, S1=>open, 
            COUT=>open);

    af_set_ctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, 
            COUT=>af_set_ctr_ci);

    af_set_ctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_setcount_0, A1=>af_setcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>af_set_ctr_ci, S0=>iaf_setcount_0, 
            S1=>iaf_setcount_1, COUT=>co0_8);

    af_set_ctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_setcount_2, A1=>af_setcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_8, S0=>iaf_setcount_2, 
            S1=>iaf_setcount_3, COUT=>co1_8);

    af_set_ctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_setcount_4, A1=>af_setcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_8, S0=>iaf_setcount_4, 
            S1=>iaf_setcount_5, COUT=>co2_8);

    af_set_ctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_setcount_6, A1=>af_setcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_8, S0=>iaf_setcount_6, 
            S1=>iaf_setcount_7, COUT=>co3_8);

    af_set_ctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_setcount_8, A1=>af_setcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_8, S0=>iaf_setcount_8, 
            S1=>iaf_setcount_9, COUT=>co4_8);

    af_set_ctr_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_setcount_10, A1=>af_setcount_11, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_8, S0=>iaf_setcount_10, 
            S1=>iaf_setcount_11, COUT=>co5_4);

    af_set_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_4);

    af_set_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_setcount_0, A1=>af_setcount_1, B0=>rcount_w0, 
            B1=>rcount_w1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci_4, S0=>open, S1=>open, 
            COUT=>co0_9);

    af_set_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_setcount_2, A1=>af_setcount_3, B0=>rcount_w2, 
            B1=>rcount_w3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_9, S0=>open, S1=>open, COUT=>co1_9);

    af_set_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_setcount_4, A1=>af_setcount_5, B0=>rcount_w4, 
            B1=>rcount_w5, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_9, S0=>open, S1=>open, COUT=>co2_9);

    af_set_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_setcount_6, A1=>af_setcount_7, B0=>rcount_w6, 
            B1=>rcount_w7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_9, S0=>open, S1=>open, COUT=>co3_9);

    af_set_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_setcount_8, A1=>af_setcount_9, 
            B0=>r_g2b_xor_cluster_0, B1=>rcount_w9, C0=>scuba_vhi, 
            C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co3_9, 
            S0=>open, S1=>open, COUT=>co4_9);

    af_set_cmp_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_setcount_10, A1=>af_set_cmp_set, B0=>rcount_w10, 
            B1=>af_set_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co4_9, S0=>open, S1=>open, 
            COUT=>af_set_c);

    a4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>af_set_c, S0=>af_set, S1=>open, 
            COUT=>open);

    af_clr_ctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, 
            COUT=>af_clr_ctr_ci);

    af_clr_ctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_clrcount_0, A1=>af_clrcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>af_clr_ctr_ci, S0=>iaf_clrcount_0, 
            S1=>iaf_clrcount_1, COUT=>co0_10);

    af_clr_ctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_clrcount_2, A1=>af_clrcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_10, S0=>iaf_clrcount_2, 
            S1=>iaf_clrcount_3, COUT=>co1_10);

    af_clr_ctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_clrcount_4, A1=>af_clrcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_10, S0=>iaf_clrcount_4, 
            S1=>iaf_clrcount_5, COUT=>co2_10);

    af_clr_ctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_clrcount_6, A1=>af_clrcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_10, S0=>iaf_clrcount_6, 
            S1=>iaf_clrcount_7, COUT=>co3_10);

    af_clr_ctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_clrcount_8, A1=>af_clrcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_10, S0=>iaf_clrcount_8, 
            S1=>iaf_clrcount_9, COUT=>co4_10);

    af_clr_ctr_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>af_clrcount_10, A1=>af_clrcount_11, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_10, S0=>iaf_clrcount_10, 
            S1=>iaf_clrcount_11, COUT=>co5_5);

    af_clr_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_5);

    af_clr_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_clrcount_0, A1=>af_clrcount_1, B0=>rcount_w0, 
            B1=>rcount_w1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci_5, S0=>open, S1=>open, 
            COUT=>co0_11);

    af_clr_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_clrcount_2, A1=>af_clrcount_3, B0=>rcount_w2, 
            B1=>rcount_w3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_11, S0=>open, S1=>open, COUT=>co1_11);

    af_clr_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_clrcount_4, A1=>af_clrcount_5, B0=>rcount_w4, 
            B1=>rcount_w5, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_11, S0=>open, S1=>open, COUT=>co2_11);

    af_clr_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_clrcount_6, A1=>af_clrcount_7, B0=>rcount_w6, 
            B1=>rcount_w7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_11, S0=>open, S1=>open, COUT=>co3_11);

    af_clr_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_clrcount_8, A1=>af_clrcount_9, 
            B0=>r_g2b_xor_cluster_0, B1=>rcount_w9, C0=>scuba_vhi, 
            C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co3_11, 
            S0=>open, S1=>open, COUT=>co4_11);

    af_clr_cmp_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>af_clrcount_10, A1=>af_clr_cmp_set, B0=>rcount_w10, 
            B1=>af_clr_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co4_11, S0=>open, 
            S1=>open, COUT=>af_clr_c);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    a5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>af_clr_c, S0=>af_clr, S1=>open, 
            COUT=>open);

    Empty <= empty_i;
    Full <= full_i;
    AlmostEmpty <= ae;
    AlmostFull <= af;
end Structure;
