/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.64.0 */
/* Module Version: 5.8 */
/* Thu Jun 30 10:30:09 2016 */

/* parameterized module instance */
cross_domain_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), 
    .AlmostEmpty( ), .AlmostFull( ));
