/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.1 */
/* Fri Jun 02 10:45:31 2017 */

/* parameterized module instance */
sc_fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .Empty( ), .Full( ));
