//===========================================================================
// Verilog file generated by Clarity Designer    09/28/2020    22:56:09  
// Filename  : csi2_dphy_dphy_rx_wrap_bb.v                                                
// IP package: CSI-2/DSI D-PHY Receiver 1.4                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_dphy_dphy_rx_wrap (
    input wire                reset_n_i,
    input wire                reset_byte_n_i,
    input wire                reset_byte_fr_n_i,
    input wire                clk_byte_fr_i,
    input wire                term_d0_en_i,
    input wire                term_d1_en_i,
    input wire                term_d2_en_i,
    input wire                term_d3_en_i,
    input wire                hs_d0_en_i,
    input wire                hs_d1_en_i,
    input wire                hs_d2_en_i,
    input wire                hs_d3_en_i,
    
    input wire [3:0]          d_sot_det, 
    input wire [3:0]          d_sote_det,
    

    input  wire               clk_byte_i, 
    input  wire [8-1:0] bd0_i,      
    input  wire [8-1:0] bd1_i,      
    input  wire [8-1:0] bd2_i,      
    input  wire [8-1:0] bd3_i,      
    output wire [8-1:0] bd0_o,      
    output wire [8-1:0] bd1_o,      
    output wire [8-1:0] bd2_o,      
    output wire [8-1:0] bd3_o,      
    output wire               hs_sync_o
);

endmodule
