//===========================================================================
// Verilog file generated by Clarity Designer    09/28/2020    22:56:09  
// Filename  : csi2_dphy_dphy_rx_wrap.v                                                
// IP package: CSI-2/DSI D-PHY Receiver 1.4                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_dphy_dphy_rx_wrap (
    input wire                reset_n_i,
    input wire                reset_byte_n_i,
    input wire                reset_byte_fr_n_i,
    input wire                clk_byte_fr_i,
    input wire                term_d0_en_i,
    input wire                term_d1_en_i,
    input wire                term_d2_en_i,
    input wire                term_d3_en_i,
    input wire                hs_d0_en_i,
    input wire                hs_d1_en_i,
    input wire                hs_d2_en_i,
    input wire                hs_d3_en_i,
    
    input wire [3:0]          d_sot_det, 
    input wire [3:0]          d_sote_det,

    input  wire               clk_byte_i, 
    input  wire [8-1:0] bd0_i,      
    input  wire [8-1:0] bd1_i,      
    input  wire [8-1:0] bd2_i,      
    input  wire [8-1:0] bd3_i,      
    output wire [8-1:0] bd0_o,      
    output wire [8-1:0] bd1_o,      
    output wire [8-1:0] bd2_o,      
    output wire [8-1:0] bd3_o,      
    output wire               hs_sync_o
);

dphy_rx_wrap
#(
  .NUM_RX_LANE            (1),
  .RX_GEAR                (8),
  .DPHY_RX_IP             ("LATTICE"),
  .LANE_ALIGN             ("OFF"),
  .WORD_ALIGN             ("ON"),
  .RX_CLK_MODE            ("HS_ONLY"),
  .BYTECLK_MHZ            (125),
  .FIFO_TYPE              ("LUT"),
  .RX_FIFO                ("ON"),
  .RX_FIFO_TYPE           ("EBR"),
  .RX_FIFO_DEPTH          (16),
  .RX_FIFO_IMPL           ("SINGLE"),
  .RX_FIFO_PKT_DLY        (1),
  .RX_FIFO_CTR_WIDTH      (1),
  .NUM_QUE_ENT            (4),
  .FR_FIFO_CLKMODE        ("DC")
)
dsi_rx (
  .reset_n_i              (reset_n_i),
  .reset_byte_n_i         (reset_byte_n_i),
  .reset_byte_fr_n_i      (reset_byte_fr_n_i),
  .clk_byte_fr_i          (clk_byte_fr_i),
  .term_d0_en_i           (term_d0_en_i),
  .term_d1_en_i           (term_d1_en_i),
  .term_d2_en_i           (term_d2_en_i),
  .term_d3_en_i           (term_d3_en_i),
  .hs_d0_en_i             (hs_d0_en_i),
  .hs_d1_en_i             (hs_d1_en_i),
  .hs_d2_en_i             (hs_d2_en_i),
  .hs_d3_en_i             (hs_d3_en_i),
  .d_sot_det              (d_sot_det), 
  .d_sote_det             (d_sote_det),
  .clk_byte_i             (clk_byte_i), 
  .bd0_i                  (bd0_i),      
  .bd1_i                  (bd1_i),      
  .bd2_i                  (bd2_i),      
  .bd3_i                  (bd3_i),      
  .bd0_o                  (bd0_o),      
  .bd1_o                  (bd1_o),      
  .bd2_o                  (bd2_o),      
  .bd3_o                  (bd3_o),      
  .hs_sync_o              (hs_sync_o)
);

endmodule
