/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.64.0 */
/* Module Version: 5.8 */
/* Fri Jul 01 12:17:59 2016 */

/* parameterized module instance */
LUT_FIFO __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
