-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 5.7
-- Wed Nov 11 00:00:54 2020

-- parameterized module component declaration
component pll_double
    port (CLKI: in  std_logic; RST: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_double
    port map (CLKI=>__, RST=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, LOCK=>__);
